# Generated by Django 4.1.6 on 2023-02-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='block',
            name='text',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
