# Generated by Django 4.1.6 on 2023-05-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_remove_block_type_block_calc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='view_type',
            field=models.CharField(choices=[('ValueLogoView', 'ValueLogoView'), ('PlainTextView', 'PlainTextView')], default='ValueLogoView', max_length=200),
            preserve_default=False,
        ),
    ]
